// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqt4vuTQH3_nBecrkqPEfOIEiGi3tybI',
    appId: '1:842937194956:web:3e421eaead80823ec66569',
    messagingSenderId: '842937194956',
    projectId: 'elearningapp-d2fe4',
    authDomain: 'elearningapp-d2fe4.firebaseapp.com',
    storageBucket: 'elearningapp-d2fe4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD35f75KPpNY9CDfyqe_nXtqn9ofW3Etjs',
    appId: '1:842937194956:android:28f53d9a00f6540dc66569',
    messagingSenderId: '842937194956',
    projectId: 'elearningapp-d2fe4',
    storageBucket: 'elearningapp-d2fe4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyqt4vuTQH3_nBecrkqPEfOIEiGi3tybI',
    appId: '1:842937194956:web:844af71abaf4789ec66569',
    messagingSenderId: '842937194956',
    projectId: 'elearningapp-d2fe4',
    authDomain: 'elearningapp-d2fe4.firebaseapp.com',
    storageBucket: 'elearningapp-d2fe4.firebasestorage.app',
  );

}